
version: 2

sources:
  - name: staging
    database: famous-muse-426921-s5
    schema: de_zoomcamp_cchow_dataset

    tables:
    - name: wildfire_polygons_raw
    - name: recreation_lines_raw


models:
  - name: stg_wildfire_polygons
    description: "Wildfire perimeters for the current fire season, including both active and inactive fires, supplied from various sources. The data is refreshed from operational systems every 15 min. These perimeters are rolled over to Historical Fire Polygons on April 1 of each year. Wildfire data is refreshed when practicable and individual fire update frequency will vary. The information is intended for general purposes only and should not be relied on as accurate because fires are dynamic and circumstances may change quickly."
    columns:
      - name: Track_date
        data_type: date
        description: ""

      - name: geometry
        data_type: geography
        description: ""
        data_tests:
          - not_null
          - unique

      - name: Fire_url
        data_type: string
        description: ""

      - name: Status
        data_type: string
        description: ""

      - name: Fire_size_Ha
        data_type: float64
        description: ""

      - name: Feature_code
        data_type: string
        description: ""

      - name: Fire_number
        data_type: string
        description: ""

      - name: Object_ID
        data_type: int64
        description: ""
        data_tests:
          - not_null
          - unique

  - name: stg_recreation_lines
    description: "This is a spatial layer showing British Columbia Ministry of Forests Recreation Lines. These are the linear spatial representation for features such as recreation trails."
    columns:
      - name: geometry
        data_type: geography
        description: ""
        data_tests:
          - not_null
          - unique

      - name: Object_ID
        data_type: int64
        description: ""
        data_tests:
          - not_null
          - unique
          
      - name: Project_date
        data_type: date
        description: ""

      - name: Feature_code
        data_type: int64
        description: ""

      - name: Project_name
        data_type: string
        description: ""

      - name: Retire_date
        data_type: date
        description: ""

      - name: Feature_length_m
        data_type: float64
        description: ""

      - name: Site_location
        data_type: string
        description: ""

      - name: Campsites
        data_type: int64
        description: ""

      - name: Trail_status
        data_type: string
        description: ""

      - name: Forest_file_ID
        data_type: string
        description: ""

      - name: Section_ID
        data_type: string
        description: ""