my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "famous-muse-426921-s5"
      dataset: "dbt_cchow"
      threads: 4 # Must be a value of 1 or greater
      keyfile: /.gc/my-creds.json
